name: cnvand-test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake>=8.0.0
  - pandas=2.2.2
  - python>=3.12
  - pytest==8.2.1
  - pillow==10.3.0
  - pdf2image==1.17.0 
  - samtools==1.20
  - snakefmt==0.10.2