name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: carlosclassen/cnvand  # Ensure this is in lowercase

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Download and Extract Annotations
      run: |
        mkdir -p data/annotations
        curl -L https://www.lbgi.fr/~geoffroy/Annotations/Annotations_Human_3.4.2.tar.gz -o data/annotations/Annotations_Human_3.4.2.tar.gz
        tar -xzvf data/annotations/Annotations_Human_3.4.2.tar.gz -C data/annotations/

    - name: Build Docker image
      id: build
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Push Docker image
      id: push
      run: |
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Verify Image Tag
      run: |
        docker images ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Tag Docker image with latest
      run: |
        docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Verify Latest Tag
      run: |
        docker images ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
